version: '2'
services:
    simplemonoexample-app:
        image: simplemonoexample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://simplemonoexample-postgresql:5432/simpleMonoExample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simplemonoexample-postgresql:
        extends:
            file: postgresql.yml
            service: simplemonoexample-postgresql
